services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Disjfa\EditorjsBundle\:
        resource: './../../*'
        exclude: './../../{Entity,Migrations,Tests}'
